### Variables, contants and Placeholders using Tensorflow 1.x (Optional)

Demo code to explain the basic concepts of Variables, contants and Placeholders

In [1]:
import tensorflow as tf #This code demo is optional to learn

#This is to just demonstrate what tensorflow 1.x does

In [2]:
one=tf.constant(1) #Lowercase c for constant

In [3]:
print(one) #We try to print one, but instead it prints out the fact it is a tensor const

Tensor("Const:0", shape=(), dtype=int32)


In [4]:
ten=tf.Variable(10) #We create a variable ten (Note this uses capital V)

In [5]:
ten #We can see it outputs that it is a variable

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

In [6]:
#tensorflow offers mathematical methods like add
#there is also operator overloading..so you can also use zero+one
sum=tf.add(ten,one)
#sum=ten+one


In [7]:
#assign method is the equivalent of "=" ...so this is same as zero=sum
update=tf.assign(ten,sum)


In [8]:
update1=tf.assign(one,sum) #We see there is an error, and the error messages in tensorflow is not as useful
#Recall, one is a constant, so it would not be applicable
#Thats the difference between constants and variables

AttributeError: 'Tensor' object has no attribute 'assign'

In [9]:
#you need this when using Variables only
#if you are using contants and placeholders - you do not need this line of code

init_op=tf.global_variables_initializer()

#This is an additional step we have to perform if we are using variables
#This creates a node called init_op, and the first thing we do when we run our session is to initilize our vars

In [10]:
sess=tf.Session()

In [11]:
sess.run(init_op) #Execute variable init_op to create variables

In [12]:
print(sess.run(update)) #We execute node update which adds ten plus one

11


In [13]:
print(sess.run(sum)) #We run the node sum which adds an additional one

12


In [ ]:
#execute update-> ten=sum-> ten + one

In [ ]:
#Placeholders

In [14]:
#not initialized to any value - unlike constants and variables
a=tf.placeholder(tf.float32) #We do not initilize it to any value, just the type of value it should hold

In [15]:
#you cannot create a variable this way
z=tf.Variable(tf.float32)

TypeError: Failed to convert object of type <class 'tensorflow.python.framework.dtypes.DType'> to Tensor. Contents: <dtype: 'float32'>. Consider casting elements to a supported type.

In [16]:
z=tf.constant(tf.float32)

TypeError: Failed to convert object of type <class 'tensorflow.python.framework.dtypes.DType'> to Tensor. Contents: <dtype: 'float32'>. Consider casting elements to a supported type.

In [17]:
a #Note that if we try to output it, we can see that it outputs the same

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [18]:
b=a*2 #Despite the placeholder not storing anything, we can still perform operations as normal

In [19]:
sess.run(b) #It will not run because it has no value in a

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[node Placeholder (defined at C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'Placeholder':
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\asyncio\base_events.py", line 438, in run_forever
    self._run_once()
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\asyncio\base_events.py", line 1451, in _run_once
    handle._run()
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\IPython\core\interactiveshell.py", line 2855, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in _run_cell
    return runner(coro)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\IPython\core\interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\IPython\core\interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-55e68eef4adf>", line 2, in <module>
    a=tf.placeholder(tf.float32)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 6669, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\archi\Anaconda3\envs\take-home-test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


In [20]:
sess.run(b,feed_dict={a:3.0}) #We run the feed_dict to pass values to our placeholder

#We pass the values in the form of a dict

6.0

In [21]:
sess.run(b,feed_dict={a:[1,2,3,4]}) #If we run, we can see each of the elements gets multiplied by 2

array([2., 4., 6., 8.], dtype=float32)

In [22]:
dictionary={a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],
                                                     [19,20,21],[22,23,24]]]} #It does not have to be a single value, but a multidimensional array


In [23]:
result=sess.run(b,feed_dict=dictionary) #We feed it the dictionary from before
print(result) #Multiplies each elements by 2

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [24]:
a=tf.placeholder(tf.float32) #What if there are multiple placeholders though?

In [25]:
b=tf.placeholder(tf.float32)

In [26]:
c= a+b #Operation on two placeholders a,b

In [27]:
result=sess.run(c,feed_dict={a:10,b:20}) #We have to pass in two values into feed_dict

In [28]:
print(result)

30.0


In [29]:
d=a*c #Let's say we want to run

In [30]:
result=sess.run(d,feed_dict={a:10,b:20}) #We pass in feed_duct a and b

#There is a sort of chain reaction, because c stores the operation of placeholder a and b being added together

In [31]:
print(result)

300.0


In [32]:
avalues=[1,2,3]
bvalues=[4,5,6] #We create arrays for a and b

In [33]:
result=sess.run(c,feed_dict={a:avalues,b:bvalues}) #And we can create a dict which feeds the arrays

In [34]:
#c=a+b
print(result)

[5. 7. 9.]


In [35]:
#d=a*c ....why are we feeding a and b instead of a and c ?!
result=sess.run(d,feed_dict={a:avalues,b:bvalues}) #We feed a and b because a and b are the variables and c is the opration

In [36]:
print(result)

[ 5. 14. 27.]


In [37]:
sess.close() #And now we use sess.close to close our session