## Data Structures for Algebra

### Scalars (Rank 0 Tensors) in Base Python

In [1]:
#Note how there is no italics
#The best behaviour is to type what type
#We create scalar tensor with 25
x = 25
x

25

In [2]:
#We use type method to find the type of variable
type(x) # if we'd like more specificity (e.g., int16, uint8), we need NumPy or another numeric library
#Note we barely use base python to create our matricies

int

In [3]:
#Create scalar y
y = 3

In [4]:
#Create sum scalar
py_sum = x + y
py_sum

28

In [5]:
type(py_sum)

int

In [6]:
#If we add a decimal at the end of our number, we make it a float
x_float = 25.0
float_sum = x_float + y #If we add an int to a float, it becomes a float in base python
float_sum #Standard behaviour across libraries

28.0

In [7]:
type(float_sum)

float

### Scalars in PyTorch

* PyTorch and TensorFlow are the two most popular *automatic differentiation* libraries in Python, which itself the most popular programming language in ML
* PyTorch tensors are designed to be pythonic, i.e., to feel and behave like NumPy arrays
* The advantage of PyTorch tensors relative to NumPy arrays is that they easily be used for operations on GPU (see [here](https://pytorch.org/tutorials/beginner/examples_tensor/two_layer_net_tensor.html) for example) 
* Documentation on PyTorch tensors, including available data types, is [here](https://pytorch.org/docs/stable/tensors.html)

In [ ]:
#Differentitation is useful for machine learning, allowing us to optimize many ML algorithms
#Python is the most popular ML languages
#Tensorflow is more popular for existing programs, but Pytorch is becoming more popular in acadamia
#In job advertisements we see Pytorch is 60% as often as TensorFlow
#They are similar enough libraries that if you know one, you can port your knowledge over
#PyTorch tensors are built to behave similar to Numpy arrays (more pythonic)
#Good for GPU operations
#Lots of speedup seen from using GPUs
#We build foundations in Pytorch because it is useful on a GPU

In [8]:
import torch #Load pytorch

In [9]:
#Create a scalar tensor by indicating a torch tensor
#We can optionally indicate we want what type we want in the variable declaration
x_pt = torch.tensor(25) # type specification optional, e.g.: dtype=torch.float16
x_pt

tensor(25)

In [10]:
#We see it has no dimensionality. so it is a scalar tensor
#Many tensors in tensors are created in a wrapper, meaning they have an extra layer of complexity
#If we want to create a variable for a tensor, we can stick with the most widely used wrapper for tensors
x_pt.shape

torch.Size([])

### Scalars in TensorFlow 

Tensors created with a wrapper, all of which [you can read about here](https://www.tensorflow.org/guide/tensor):  

* `tf.Variable`
* `tf.constant`
* `tf.placeholder`
* `tf.SparseTensor`

Most widely-used is `tf.Variable`, which we'll use here. 

As with TF tensors, in PyTorch we can similarly perform operations, and we can easily convert to and from NumPy arrays

Also, a full list of tensor data types is available [here](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType).

In [11]:
#Import the tensorflow library
import tensorflow as tf

In [12]:
#We use tf.var to use tensorflow
x_tf = tf.Variable(25, dtype=tf.int16) # dtype is optional
x_tf #We can see the output is somewhat not pythonic

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [13]:
x_tf.shape #No dimensionality, so scalar

TensorShape([])

In [14]:
y_tf = tf.Variable(3, dtype=tf.int16) #We create variable y with a value of 3 in it

In [15]:
x_tf + y_tf #We add them together to get 25+3 to get 28, and still a 16 bit integer
#We can use base python operator to add the two tensorflow and pytorch variables
#This is due to overloading

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [16]:
tf_sum = tf.add(x_tf, y_tf) #We can also do sums
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [17]:
tf_sum.numpy() # note that NumPy operations automatically convert tensors to NumPy arrays, and vice versa

28

In [18]:
type(tf_sum.numpy())

numpy.int16

In [19]:
tf_float = tf.Variable(25., dtype=tf.float16) #We perform the same variable creation but this time we use a float, and to no surprise the variable is type float
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

### Vectors (Rank 1 Tensors) in NumPy

In [20]:
#We use numpy here because we cannot create 1D arrays in base python
#We create an array with the defined elements, and note we can set the dtype here as well
import numpy as np
x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

In [21]:
len(x) #Array of length 3

3

In [22]:
x.shape #3 rows, no height

(3,)

In [23]:
type(x) #We can see we have a numpy array

numpy.ndarray

In [24]:
#Arrays start at zero
x[0] # zero-indexed

25

In [25]:
type(x[0]) #We can see the individual variable is an integer

numpy.int32

### Vector Transposition

In [26]:
# Transposing a regular 1-D array has no effect...
x_t = x.T
x_t 

array([25,  2,  5])

In [27]:
x_t.shape #Looks the same, but we see the limitation of using this

(3,)

In [28]:
# ...but it does we use nested "matrix-style" brackets: 
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [29]:
y.shape #Now we can see it is 1 row and 3 cols

(1, 3)

In [30]:
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent: 
y_t = y.T
y_t #And now we can see it is the transposed vector

array([[25],
       [ 2],
       [ 5]])

In [31]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [32]:
# Column vector can be transposed back to original row vector: 
y_t.T  #And we can change it back here

array([[25,  2,  5]])

In [33]:
y_t.T.shape #1 row, 3 length

(1, 3)

### Zero Vectors

Have no effect if added to another vector

In [34]:
z = np.zeros(3) 
z #If we add a zero vector to another, it has no effect

array([0., 0., 0.])

### Vectors in PyTorch and TensorFlow

In [35]:
x_pt = torch.tensor([25, 2, 5]) #We define our elements explicitly
x_pt

tensor([25,  2,  5])

In [36]:
x_tf = tf.Variable([25, 2, 5]) #In tensorflow, sane situation
x_tf #Tensorflow gives a verbose output

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

### $L^2$ Norm

In [37]:
x

array([25,  2,  5])

In [38]:
(25**2 + 2**2 + 5**2)**(1/2) #Manual calculation of the L2 norm (our example is in 3d space because 3 coordinates)

25.573423705088842

In [39]:
np.linalg.norm(x) #We can also use numpy to calculate this, which is also the same result

25.573423705088842

So, if units in this 3-dimensional vector space are meters, then the vector $x$ has a length of 25.6m

### $L^1$ Norm

In [40]:
x

array([25,  2,  5])

In [41]:
np.abs(25) + np.abs(2) + np.abs(5) #We can manually calculate the norm by taking the abs of each coordinate and we can see we get 32

32

### Squared $L^2$ Norm

In [42]:
x

array([25,  2,  5])

In [43]:
(25**2 + 2**2 + 5**2) #We get a pretty large number

654

In [44]:
# we'll cover tensor multiplication more soon but to prove point quickly: 
np.dot(x, x) #We calculate this very cheaply by using the dot product here

654

### Max Norm

In [45]:
x

array([25,  2,  5])

In [46]:
np.max([np.abs(25), np.abs(2), np.abs(5)]) #We take the max of the absolute values of an array

25

**Return to slides here.**

### Orthogonal Vectors

In [47]:
i = np.array([1, 0])
i

array([1, 0])

In [48]:
j = np.array([0, 1])
j

array([0, 1])

In [49]:
np.dot(i, j) # detail on the dot operation coming up... 
#We can see these orthogonal vectors have a dot product of zero

0

### Matrices (Rank 2 Tensors) in NumPy

In [50]:
# Use array() with nested brackets: 
X = np.array([[25, 2], [5, 26], [3, 7]]) #We have to use double square brackets, where the outer pair of brackets are the entire matrix
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [51]:
X.shape #3 rows and 2 cols

(3, 2)

In [52]:
X.size #6 total elements

6

In [53]:
# Select left column of matrix X (zero-indexed)
X[:,0] #If we only want to grab the first column, or column zero in python (leftmost)

array([25,  5,  3])

In [54]:
# Select middle row of matrix X: 
X[1,:] #Grab middle row 

array([ 5, 26])

In [55]:
# Another slicing-by-index example: 
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

### Matrices in PyTorch

In [56]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]]) #Create matrix tensor
X_pt #In pytorch it looks pretty similar

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [57]:
X_pt.shape # more pythonic

torch.Size([3, 2])

In [58]:
X_pt[1,:]

tensor([ 5, 26])

### Matrices in TensorFlow

In [59]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]]) #Tensorflow has a few quarks, but not too far away, but recall we once again use the double brackets
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [60]:
tf.shape(X_tf) #We have to call the tensorflow shape method specifically
#We see the rank is 2, and has 3 rows and 2 cols

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [61]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [62]:
X_tf[1,:] #Slicing is the same as in pytorch and numpy

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>

### Higher-Rank Tensors

As an example, rank 4 tensors are common for images, where each dimension corresponds to: 

1. Number of images in training batch, e.g., 32
2. Image height in pixels, e.g., 28 for [MNIST digits](http://yann.lecun.com/exdb/mnist/)
3. Image width in pixels, e.g., 28
4. Number of color channels, e.g., 3 for full-color images (RGB)

In [63]:
#Imagine we have a full colour image and we want to determine whether it is an image of a cat or dog
#Above is the 4 dimensions of a digital image
images_pt = torch.zeros([32, 28, 28, 3]) 

In [64]:
# images_pt

In [65]:
images_tf = tf.zeros([32, 28, 28, 3])

In [66]:
# images_tf