## Common Tensor Operations in Linear Algebra

### Tensor Transposition

In [1]:
import torch
import tensorflow as tf
import numpy as np

X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [2]:
X.T #We can see the elements that were for example in the ith row move only to the ith col

array([[25,  5,  3],
       [ 2, 26,  7]])

In [3]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]]) #Pytorch has a similar syntax as python/numpy
X_pt.T 

tensor([[25,  5,  3],
        [ 2, 26,  7]])

In [4]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]]) #Tensorflow is less pythonic
tf.transpose(X_tf) # less Pythonic

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]])>

### Basic Arithmetical Properties

Adding or multiplying with scalar applies operation to all elements and tensor shape is retained: 

In [5]:
X*2 #Applies the scalar to all the elements (Note that we use the matrix from above)

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [6]:
X+2 #Adds two to each element 

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [7]:
X*2+2 #Multiplies by two and adds two to each element

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [8]:
X_pt*2+2 # Python operators are overloaded; could alternatively use torch.mul() or torch.add()
#Python operators are overloaded when we use pytorch or tensorflow tensors

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [9]:
torch.add(torch.mul(X_pt, 2), 2) #We can use the actual pytorch addition and multiplation, which gives the same result

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [10]:
X_tf*2+2 # Operators likewise overloaded; could equally use tf.multiply() tf.add()

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [11]:
tf.add(tf.multiply(X_tf, 2), 2) #We use the tensorflow operators 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

If two tensors have the same size, operations are often by default applied element-wise. This is **not matrix multiplication**, but is rather called simply the **element-wise product**. 

The mathematical notation is $A \odot X$

In [12]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [13]:
A = X+2 #We create a new matrix A but added 2 to each element
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [14]:
A + X #Element to element addition

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [15]:
A * X #We do multiplication with the python asterisk

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [16]:
A_pt = X_pt + 2 

In [17]:
A_pt + X_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [18]:
A_pt * X_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In [19]:
A_tf = X_tf + 2 #Pytorch and tensorflow and numpy have the same across all differing types of tensors

In [20]:
A_tf + X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [21]:
A_tf * X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]])>

### Reduction

Calculating the sum across all elements of a tensor is a common operation. For example: 

* For vector ***x*** of length *n*, we calculate $\sum_{i=1}^{n} x_i$
* For matrix ***X*** with *m* by *n* dimensions, we calculate $\sum_{i=1}^{m} \sum_{j=1}^{n} X_{i,j}$

In [22]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [23]:
X.sum() #In numpy we use sum

68

In [24]:
torch.sum(X_pt) #In torch, it uses sum as well

tensor(68)

In [25]:
tf.reduce_sum(X_tf) #Also same process

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [26]:
# Can also be done along one specific axis alone, e.g.:
X.sum(axis=0) # summing all rows (axis=0 means rows)

array([33, 35])

In [27]:
X.sum(axis=1) # summing all columns (axis=1 means cols)

array([27, 31, 10])

In [28]:
torch.sum(X_pt, 0) #Similar process for pytorch and tesnorflow but instead we use as a second arg the row/col

tensor([33, 35])

In [29]:
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10])>

Many other operations can be applied with reduction along all or a selection of axes, e.g.:

* maximum
* minimum
* mean
* product

They're fairly straightforward and used less often than summation, so you're welcome to look them up in library docs if you ever need them.

### The Dot Product

If we have two vectors (say, ***x*** and ***y***) with the same length *n*, we can calculate the dot product between them. This is annotated several different ways, including the following: 

* $x \cdot y$
* $x^Ty$
* $\langle x,y \rangle$

Regardless which notation you use (I prefer the first), the calculation is the same; we calculate products in an element-wise fashion and then sum reductively across the products to a scalar value. That is, $x \cdot y = \sum_{i=1}^{n} x_i y_i$

The dot product is ubiquitous in deep learning: It is performed at every artificial neuron in a deep neural network, which may be made up of millions (or orders of magnitude more) of these neurons.

In [30]:
#At every neuron, the dot product is performed
x= np.array([25, 2, 5])
x

array([25,  2,  5])

In [31]:
y = np.array([0, 1, 2])
y

array([0, 1, 2])

In [32]:
25*0 + 2*1 + 5*2

12

In [33]:
np.dot(x, y)

12

In [34]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [35]:
y_pt = torch.tensor([0, 1, 2])
y_pt

tensor([0, 1, 2])

In [36]:
np.dot(x_pt, y_pt)

12

In [37]:
torch.dot(torch.tensor([25, 2, 5.]), torch.tensor([0, 1, 2.])) #In pytorch, a lot of these pytorch oprations dont work on integer type pytorch tensors, so you need to pass in a float
#Specify a decimal point on any of the elements to make them float type. allowing us to perform the dot product (scalar float)

tensor(12.)

In [38]:
x_tf= tf.Variable([25, 2, 5]) 
x_tf 

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

In [39]:
y_tf = tf.Variable([0, 1, 2])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2])>

In [40]:
tf.reduce_sum(tf.multiply(x_tf, y_tf)) #In tensorflow, there is not a built in dot product, so we have to improvise by doing a manual calculation

<tf.Tensor: shape=(), dtype=int32, numpy=12>